# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
