# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_dog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='likes',
        ),
    ]
